# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_ill.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_3(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 170)
        self.diag_lbl = QtWidgets.QLabel(Dialog)
        self.diag_lbl.setGeometry(QtCore.QRect(10, 80, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.diag_lbl.setFont(font)
        self.diag_lbl.setObjectName("diag_lbl")
        self.id = QtWidgets.QLineEdit(Dialog)
        self.id.setGeometry(QtCore.QRect(90, 20, 261, 20))
        self.id.setObjectName("id")
        self.id_lbl = QtWidgets.QLabel(Dialog)
        self.id_lbl.setGeometry(QtCore.QRect(10, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.id_lbl.setFont(font)
        self.id_lbl.setObjectName("id_lbl")
        self.okIll_btn = QtWidgets.QPushButton(Dialog)
        self.okIll_btn.setGeometry(QtCore.QRect(150, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.okIll_btn.setFont(font)
        self.okIll_btn.setObjectName("okIll_btn")
        self.diag = QtWidgets.QLineEdit(Dialog)
        self.diag.setGeometry(QtCore.QRect(90, 80, 261, 20))
        self.diag.setObjectName("diag")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 145, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.diag_lbl.setText(_translate("Dialog", "Диагноз:"))
        self.id_lbl.setText(_translate("Dialog", "ID пациента:"))
        self.okIll_btn.setText(_translate("Dialog", "ОК"))
