# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'illness.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_1(object):
    def setupUi(self, Form_1):
        Form_1.setObjectName("Form_1")
        Form_1.resize(520, 690)
        self.gridLayoutWidget = QtWidgets.QWidget(Form_1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-2, 0, 521, 651))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.delill_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.delill_btn.setObjectName("delill_btn")
        self.gridLayout.addWidget(self.delill_btn, 1, 1, 1, 1)
        self.showill_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.showill_btn.setObjectName("showill_btn")
        self.gridLayout.addWidget(self.showill_btn, 1, 2, 1, 1)
        self.chngill_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.chngill_btn.setObjectName("chngill_btn")
        self.gridLayout.addWidget(self.chngill_btn, 1, 3, 1, 1)
        self.addill_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.addill_btn.setObjectName("addill_btn")
        self.gridLayout.addWidget(self.addill_btn, 1, 0, 1, 1)
        self.chsill_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.chsill_btn.setObjectName("chsill_btn")
        self.gridLayout.addWidget(self.chsill_btn, 0, 0, 1, 1)
        self.ill_table = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.ill_table.setLineWidth(1)
        self.ill_table.setObjectName("ill_table")
        self.ill_table.setColumnCount(2)
        self.ill_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.ill_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ill_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ill_table.setHorizontalHeaderItem(1, item)
        self.ill_table.horizontalHeader().setVisible(True)
        self.ill_table.horizontalHeader().setCascadingSectionResizes(False)
        self.ill_table.horizontalHeader().setDefaultSectionSize(250)
        self.gridLayout.addWidget(self.ill_table, 2, 0, 1, 5)
        self.srchill_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.srchill_btn.setObjectName("srchill_btn")
        self.gridLayout.addWidget(self.srchill_btn, 0, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 3)
        self.label_msg = QtWidgets.QLabel(Form_1)
        self.label_msg.setGeometry(QtCore.QRect(0, 650, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_msg.setFont(font)
        self.label_msg.setText("")
        self.label_msg.setObjectName("label_msg")

        self.retranslateUi(Form_1)
        QtCore.QMetaObject.connectSlotsByName(Form_1)

    def retranslateUi(self, Form_1):
        _translate = QtCore.QCoreApplication.translate
        Form_1.setWindowTitle(_translate("Form_1", "Form"))
        self.delill_btn.setText(_translate("Form_1", "Удалить данные"))
        self.showill_btn.setText(_translate("Form_1", "Показать всё"))
        self.chngill_btn.setText(_translate("Form_1", "Изменть данные"))
        self.addill_btn.setText(_translate("Form_1", "Добавить болезнь"))
        self.chsill_btn.setText(_translate("Form_1", "ID"))
        item = self.ill_table.verticalHeaderItem(0)
        item.setText(_translate("Form_1", "1"))
        item = self.ill_table.horizontalHeaderItem(0)
        item.setText(_translate("Form_1", "ID карты"))
        item = self.ill_table.horizontalHeaderItem(1)
        item.setText(_translate("Form_1", "Диагноз"))
        self.srchill_btn.setText(_translate("Form_1", "Искать"))
        self.lineEdit.setText(_translate("Form_1", "1"))
